// DEMO MODE — remplacer par les vrais appels Supabase quand prêt
import type { Notification } from "@/types";
export const DEMO = {
  user: {
    first_name: "Thomas",
    last_name: "B.",
  },
  metrics: {
    mrr: "13 100 €",
    mrrTrend: "+7% ce mois",
    runway: "7,8 mois",
    runwayStatus: "warning" as const,
    priorite: "Finaliser pitch deck",
    alertes: 2,
  },
  activity: [
    { icon: "📊", text: "Runway mis à jour", sub: "Elyse · trésorerie synchronisée", time: "il y a 1h" },
    { icon: "🎯", text: "Nouveau prospect ajouté", sub: "Gyna · FinStart SAS", time: "il y a 3h" },
    { icon: "✅", text: "Contrat signé — Camille Martin", sub: "Gyna · 4 200 €", time: "hier" },
    { icon: "⚠️", text: "Burn en hausse de 18%", sub: "Elyse · alerte déclenchée", time: "hier" },
    { icon: "📝", text: "Business Plan mis à jour", sub: "Elyse · Livrables", time: "il y a 2j" },
  ],
  tools: [
    { status: "Actif", progress: 85 },
    { status: "Actif", progress: 72 },
    { status: "Actif", progress: 91 },
  ],
  notifications: [
    {
      id: "1",
      user_id: "demo",
      tool: "elyse" as const,
      type: "critique" as const,
      title: "Runway sous le seuil critique",
      message: "7,8 mois de runway — en dessous du seuil recommandé de 9 mois.",
      link: "/elyse",
      is_read: false,
      email_sent: false,
      created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    },
    {
      id: "2",
      user_id: "demo",
      tool: "elyse" as const,
      type: "warning" as const,
      title: "Burn mensuel en hausse",
      message: "+18% vs mois dernier — identifier les postes en hausse.",
      link: "/elyse",
      is_read: false,
      email_sent: false,
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    },
    {
      id: "3",
      user_id: "demo",
      tool: "gyna" as const,
      type: "rappel" as const,
      title: "Relance Sophie Arnaud",
      message: "J+5 sans réponse — Growlab. Planifier une relance.",
      link: "/gyna",
      is_read: false,
      email_sent: false,
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    },
    {
      id: "4",
      user_id: "demo",
      tool: "astryd" as const,
      type: "rappel" as const,
      title: "Call investisseur dans 2 jours",
      message: "Préparer le pitch deck V2 avant le 28 avril.",
      link: "/astryd",
      is_read: true,
      email_sent: false,
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    },
  ] as Notification[],
};
